### ISSUE TITLE
[BUG] Don't print `Error: No module named '__lldb_python_module_n'` when Python errors in the notebook

### ISSUE THREAD

**Issue by DayDun** [modular/max#231]
## Bug Description

When using `%%python`  in a cell and Python raises an exception, there is an additional `Error: No module named '__lldb_python_module_n'` appended to the output
```py
%%python
a = 1 / 0
```
```
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "<string>", line 33, in <module>
ZeroDivisionError: division by zero
Error: No module named '__lldb_python_module_8'
```

Expected behavior would be for this extra line to not get printed. Minor cosmetic thing, but thought I'd bring it up.

### Steps to Reproduce

Run the provided code.

### Context
```
11:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0d9a6497_fe5c_4a80_9d7e_1166ef3b9f5f.slice/cri-containerd-9f489e4d647b49bf3a790d5141ef0bb3dc6ce340dc9ff74e0ea10b6df802d05f.scope
10:devices:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0d9a6497_fe5c_4a80_9d7e_1166ef3b9f5f.slice/cri-containerd-9f489e4d647b49bf3a790d5141ef0bb3dc6ce340dc9ff74e0ea10b6df802d05f.scope
9:blkio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0d9a6497_fe5c_4a80_9d7e_1166ef3b9f5f.slice/cri-containerd-9f489e4d647b49bf3a790d5141ef0bb3dc6ce340dc9ff74e0ea10b6df802d05f.scope
8:cpu,cpuacct:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0d9a6497_fe5c_4a80_9d7e_1166ef3b9f5f.slice/cri-containerd-9f489e4d647b49bf3a790d5141ef0bb3dc6ce340dc9ff74e0ea10b6df802d05f.scope
7:memory:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0d9a6497_fe5c_4a80_9d7e_1166ef3b9f5f.slice/cri-containerd-9f489e4d647b49bf3a790d5141ef0bb3dc6ce340dc9ff74e0ea10b6df802d05f.scope
6:pids:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0d9a6497_fe5c_4a80_9d7e_1166ef3b9f5f.slice/cri-containerd-9f489e4d647b49bf3a790d5141ef0bb3dc6ce340dc9ff74e0ea10b6df802d05f.scope
5:cpuset:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0d9a6497_fe5c_4a80_9d7e_1166ef3b9f5f.slice/cri-containerd-9f489e4d647b49bf3a790d5141ef0bb3dc6ce340dc9ff74e0ea10b6df802d05f.scope
4:perf_event:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0d9a6497_fe5c_4a80_9d7e_1166ef3b9f5f.slice/cri-containerd-9f489e4d647b49bf3a790d5141ef0bb3dc6ce340dc9ff74e0ea10b6df802d05f.scope
3:hugetlb:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0d9a6497_fe5c_4a80_9d7e_1166ef3b9f5f.slice/cri-containerd-9f489e4d647b49bf3a790d5141ef0bb3dc6ce340dc9ff74e0ea10b6df802d05f.scope
2:net_cls,net_prio:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0d9a6497_fe5c_4a80_9d7e_1166ef3b9f5f.slice/cri-containerd-9f489e4d647b49bf3a790d5141ef0bb3dc6ce340dc9ff74e0ea10b6df802d05f.scope
1:name=systemd:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod0d9a6497_fe5c_4a80_9d7e_1166ef3b9f5f.slice/cri-containerd-9f489e4d647b49bf3a790d5141ef0bb3dc6ce340dc9ff74e0ea10b6df802d05f.scope
0::/
```

**Comment by Mogball** [comment]
Seems reasonable. @walter-erquinigo @River707
